chore: Edited the query filter to remove .get()
firebase/snippets-node pull request #377
Opened 2023-11-27 12:17 UTC by shweta345

Updated the code to resolve a customer feedback about understanding simple queries due to the .get() function.

2023-11-27 15:33 UTC, thatfiredev commented
Hey @shweta345 
Can you please describe what issue the customer was running into? Links to public Github issues or internal bug tickets are welcome. Thanks!

2023-11-28 04:14 UTC, shweta345 commented
@thatfiredev Internal bug ID that it targets is http://b/300413440. I was unsure if I should link it here :)

2023-11-28 11:24 UTC, thatfiredev commented
@shweta345 I do see the 2 simple queries that the customer seems to be talking about:

<img width="935" alt="Screenshot 2023-11-28 at 11 22 29" src="https://github.com/firebase/snippets-node/assets/16766726/2bf5da4e-798c-4cef-9f6b-caa7f9c2c989">



But they don't seem to match with the query you're updating in this PR: 

https://github.com/shweta345/snippets-node/blob/c234a3db471da94e5c9be8a29d856e4a8df9e31e/firestore/main/index.js#L590

2023-11-28 11:33 UTC, shweta345 commented
@thatfiredev This is the link that customer has shared: https://cloud.google.com/firestore/docs/query-data/queries#simple_queries. If you see the second snippet, it is the one that I edited.

2023-11-28 11:35 UTC, thatfiredev requested changes
@shweta345 Ah, my bad. I was looking at the wrong snippet (modular SDK)

One minor change needed before we merge this:

2023-11-28 11:35 UTC, thatfiredev commented on firestore/main/index.js
> +  const allCapitalsRes = await citiesRef.where('capital', '==', true);
We can get rid of the `await` as well:
```suggestion
  const allCapitalsRes = citiesRef.where('capital', '==', true);
```

2023-11-28 11:36 UTC, shweta345 commented
@thatfiredev Merged your edits. Thank you! :)

2023-11-28 11:37 UTC, thatfiredev approved these changes
LGTM
Thanks for updating this :)

2023-11-28 11:39 UTC, merged